# This docker-compose.yml creates a Storage as a Service (StaaS), by using the NextCloud platform.
# The NextCLoud is behind a Reverse Proxy (Nginx) with SSL Encryption (LetsEcrypt).
# This implementation uses MariaDB as database for the NextCloud.
#
# Special thanks to the following github users:
#   - https://github.com/nextcloud/docker
#   - https://github.com/jwilder/nginx-proxy
#   - https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
#

version: '2'

services:

#-----------------------------------------------------------------------------------#
###################################### NEXTCLOUD ####################################
#-----------------------------------------------------------------------------------#

  # MySQL Database for NextCloud

  db:
    image: mariadb
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /media/storage/nextcloud/db:/var/lib/mysql
    env_file:
      - nextcloud_db.env
    networks:
      - proxy-tier
    restart: always

  # Nextcloud App

  app:
    image: nextcloud:fpm
    container_name: nextcloud_fpm
    links:
      - db
    volumes:
      - /media/storage/nextcloud/web:/var/www/html
    networks:
      - proxy-tier
    restart: always
    depends_on:
      - db
  
  # Nginx Webserver for NextCloud

  web:
    image: nginx
    container_name: nextcloud_web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
    env_file:
      - nextcloud_web.env
    networks:
      - proxy-tier
    restart: always
    depends_on:
      - app

#------------------------------------------------------------------------------------#
######################################## GITEA #######################################
#------------------------------------------------------------------------------------#
  
  # Gitea App

  gitea:
    image: gitea/gitea:latest
    container_name: gitea_app
    volumes:
      - /media/storage/gitea/gitea_data:/data
    depends_on:
      - gitea_db
    links:
      - gitea_db
    restart: always
    ports:
      - "3000:3000"
      - "22:22"
    networks:
      - proxy-tier
    environment:
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
    env_file:
      - gitea_app.env

  # MySQL Database for Gitea

  gitea_db:
    image: mariadb:latest
    container_name: gitea_db
    restart: always
    env_file:
      - gitea_db.env
    networks:
      - proxy-tier
    volumes:
      - /media/storage/gitea/gitea_db/:/var/lib/mysql

#------------------------------------------------------------------------------------#
######################################## PROXY #######################################
#------------------------------------------------------------------------------------#

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /media/storage/nextcloud/proxy/conf.d:/etc/nginx/conf.d
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
      - /media/storage/nextcloud/proxy/vhost.d:/etc/nginx/vhost.d
      - /media/storage/nextcloud/proxy/html:/usr/share/nginx/html
      - /media/storage/nextcloud/proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    restart: always
    depends_on:
      - web
      
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/storage/nextcloud/proxy/certs:/etc/nginx/certs:rw
    restart: always
    depends_on:
      - proxy

#------------------------------------------------------------------------------------#
###################################### NETWORKS ######################################
#------------------------------------------------------------------------------------#

networks:
  proxy-tier:
    external:
      name: nginx-proxy
